"""Create User Model

Revision ID: a2d31f5702e4
Revises: 
Create Date: 2022-07-05 00:38:34.004619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d31f5702e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False, comment='이메일'),
    sa.Column('nickname', sa.String(), nullable=False, comment='닉네임'),
    sa.Column('password', sa.String(), nullable=False, comment='비밀번호'),
    sa.Column('name', sa.String(), nullable=False, comment='이름'),
    sa.Column('phone_number', sa.Integer(), nullable=False, comment='전화번호'),
    sa.Column('is_activate', sa.Boolean(), nullable=True, comment='로그인 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nickname'),
    sa.UniqueConstraint('phone_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
