"""Add user_token Field

Revision ID: a43236b8674f
Revises: a2d31f5702e4
Create Date: 2022-07-06 10:47:13.355098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a43236b8674f'
down_revision = 'a2d31f5702e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_token', sa.String(), nullable=False, comment='유저 토큰'))
    op.create_index(op.f('ix_user_user_token'), 'user', ['user_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_user_token'), table_name='user')
    op.drop_column('user', 'user_token')
    # ### end Alembic commands ###
